Repository Uninett/nav, pull requests merged in 2019-02, with the labels that each got.

#1822 Command line argument support for nav daemon startup config
  python/nav/startstop.py
Labels: bug

#1837 Save config to non volatile memory in portadmin for dell switches
  python/nav/portadmin/snmputils.py
Labels: enhancement

#1843 Misc python3 fixes
  python/nav/asyncdns.py
  python/nav/ipdevpoll/plugins/sensors.py
  python/nav/macaddress.py
  python/nav/models/profiles.py
  python/nav/portadmin/snmputils.py
  python/nav/web/ipam/prefix_tree.py
  python/nav/web/report/views.py
  python/nav/web/seeddb/forms/bulk.py
Labels: cleanup, python3

#1851 Fix searching for other things than ip addresses in portadmin
  python/nav/web/portadmin/views.py
Labels: bug

#1849 Remove all references to render_to_response
  python/nav/eventengine/alerts.py
  python/nav/web/alertprofiles/shortcuts.py
  python/nav/web/alertprofiles/views.py
  python/nav/web/arnold/views.py
  python/nav/web/devicehistory/views.py
  python/nav/web/geomap/views.py
  python/nav/web/info/location/views.py
  python/nav/web/info/room/views.py
  python/nav/web/info/views.py
  python/nav/web/info/vlan/views.py
  python/nav/web/ipam/views.py
  python/nav/web/ipdevinfo/context_processors.py
  python/nav/web/ipdevinfo/views.py
  python/nav/web/l2trace/views.py
  python/nav/web/machinetracker/views.py
  python/nav/web/macwatch/views.py
  python/nav/web/maintenance/views.py
  python/nav/web/messages/views.py
  python/nav/web/navlets/__init__.py
  python/nav/web/portadmin/views.py
  python/nav/web/radius/views.py
  python/nav/web/report/views.py
  python/nav/web/seeddb/page/__init__.py
  python/nav/web/seeddb/page/prefix.py
  python/nav/web/seeddb/page/service/edit.py
  python/nav/web/seeddb/utils/bulk.py
  python/nav/web/seeddb/utils/delete.py
  python/nav/web/seeddb/utils/edit.py
  python/nav/web/seeddb/utils/list.py
  python/nav/web/seeddb/utils/move.py
  python/nav/web/status2/views.py
  python/nav/web/syslogger/views.py
Labels: cleanup, django

#1850 Fix connectivity check for snmp with write access in seeddb on python3
  python/nav/Snmp/__init__.py
  python/nav/Snmp/pynetsnmp.py
  python/nav/ipdevpoll/plugins/interfaces.py
  python/nav/ipdevpoll/plugins/sensors.py
  python/nav/ipdevpoll/shadows/interface.py
  python/nav/web/seeddb/page/netbox/edit.py
  tests/unittests/Snmp/encodings_test.py
  tests/unittests/ipdevpoll/interfaces_test.py
Labels: python3

#1854 (ipdevpoll) Save netbox poll timestamps in database as json
  python/nav/ipdevpoll/timestamps.py
Labels: cleanup, python3

#1864 Remove unused files
  python/nav/web/cycler.py
  python/nav/web/preferences.py
Labels: cleanup
