Repository Uninett/nav, pull requests merged in 2019-06, with the labels that each got.

#1960 Add option to control user administrator privileges from LDAP
  doc/reference/ldap.rst
  python/nav/etc/webfront/webfront.conf
  python/nav/web/auth.py
  python/nav/web/ldapauth.py
  tests/unittests/general/webfront_test.py
Labels: enhancement

#1859 Improve portadmin support for dot1x
  python/nav/etc/portadmin/portadmin.conf
  python/nav/portadmin/snmputils.py
  python/nav/smidumps/CISCO-PAE-MIB.py
  python/nav/web/portadmin/utils.py
  python/nav/web/portadmin/views.py
  python/nav/web/sass/nav/_table.scss
  python/nav/web/templates/portadmin/portlist.html
Labels: enhancement, portadmin

#1963 Drop support for old pickled timestamps.
  python/nav/ipdevpoll/timestamps.py
  tests/unittests/ipdevpoll/timestamps_test.py
Labels: cleanup

#1968 Make EventMixIn and ThresholdEvent work properly on Django >= 1.11
  python/nav/models/event.py
  tests/unittests/models/event_test.py
Labels: cleanup, django

#1967 Fix binary/string/unicode issues in the neighbor discovery system when running under Python 3
  python/nav/ipdevpoll/neighbor.py
  python/nav/ipdevpoll/plugins/cdp.py
  python/nav/ipdevpoll/plugins/lldp.py
  python/nav/ipdevpoll/shadows/__init__.py
  python/nav/ipdevpoll/shadows/adjacency.py
  python/nav/ipdevpoll/utils.py
  python/nav/mibs/lldp_mib.py
  tests/unittests/ipdevpoll/neighbor_test.py
Labels: cleanup, python3

#1969 Store local chassis ids from LLDP-MIB and use for neighbor lookups
  python/nav/ipdevpoll/plugins/lldp.py
  python/nav/mibs/mibretriever.py
  python/nav/models/sql/changes/sc.04.10.0020.sql
Labels: enhancement, lldp

#1943 Improve support for boolean sensors in racks
  python/nav/ipdevpoll/plugins/sensors.py
  python/nav/mibs/comet.py
  python/nav/mibs/eltek_distributed_mib.py
  python/nav/mibs/pdu2_mib.py
  python/nav/models/manage.py
  python/nav/models/rack.py
  python/nav/models/sql/changes/sc.04.10.0050.sql
  python/nav/web/api/v1/serializers.py
  python/nav/web/ipdevinfo/forms.py
  python/nav/web/ipdevinfo/views.py
  python/nav/web/navlets/__init__.py
  python/nav/web/sass/nav/rack.scss
  python/nav/web/static/js/resources/vue/environment_rack_item.html
  python/nav/web/static/js/src/info_room_rack.js
  python/nav/web/static/js/src/plugins/vue_rack.js
  python/nav/web/static/js/src/sensor_details.js
  python/nav/web/templates/info/room/fragment_racksensor.html
  python/nav/web/templates/ipdevinfo/sensor-details.html
Labels: enhancement
