Repository Uninett/nav, pull requests merged in 2023-03, with the labels that each got.

#2594 Make save function of Alert/EventQueue and AlertHistory atomic
  CHANGELOG.md
  python/nav/models/event.py
  tools/eventgenerators/devicenotice.py
Labels: bug

#2516 Update SNMP forwarding/proxying examples in docker-compose environment
  docker-compose.snmp.yml
  docker-compose.yml
  tools/forward/Dockerfile
Labels: snmp, docker

#2599 Add unit tests for ipdevpoll worker euthanization
  tests/unittests/ipdevpoll/pool_test.py
Labels: tests

#2602 Drop obsolete Python 2 compatibility statement
  python/nav/eventengine/alerts.py
Labels: cleanup

#2605 Never restore stale tox environment caches in GitHub workflows
  .github/workflows/build-and-test.yml
Labels: tests

#2596 Fix backwards relation references in group search
  CHANGELOG.md
  python/nav/web/info/netboxgroup/views.py
Labels: bug
