Repository Uninett/nav, pull requests merged in 2023-11, with the labels that each got.

#2705 Add command to bin/navuser to remove user
  bin/navuser
Labels: useradmin

#2720 Fix broken docs environment in tox.ini
  pyproject.toml
  tox.ini
Labels: documentation

#2699 Add an SNMPv3 management profile type
  python/nav/models/manage.py
  python/nav/web/seeddb/page/management_profile/forms.py
  python/nav/web/templates/seeddb/management-profile/edit.html
  tests/unittests/seeddb/management_profile_test.py
Labels: enhancement, snmpv3

#2732 Fix (de)activating alert profiles
  python/nav/web/alertprofiles/views.py
  tests/integration/web/alertprofiles_test.py
Labels: bug

#2710 Add SNMPv3 support to nav.Snmp.pynetsnmp implementation #2703
  python/nav/Snmp/defines.py
  python/nav/Snmp/errors.py
  python/nav/Snmp/pynetsnmp.py
Labels: enhancement, snmpv3

#2734 Enable SNMPv3 reachability verification in SeedDB
  python/nav/Snmp/profile.py
  python/nav/web/seeddb/page/netbox/edit.py
  tests/unittests/Snmp/profile_test.py
Labels: enhancement, snmpv3

#2737 Fix broken navoidverify on Linux
  bin/navoidverify
Labels: bug

#2725 Add SNMPv3 support to navsnmp command
  bin/navsnmp
Labels: enhancement, snmpv3

#2730 Enable SNMPv3 write profile checks in SeedDB
  python/nav/web/seeddb/page/netbox/edit.py
  tools/snmpdv3/Dockerfile
  tools/snmpdv3/README.md
  tools/snmpdv3/snmpd.conf
Labels: enhancement, snmpv3

#2733 Add SNMPv3 support to Arnold
  python/nav/arnold.py
  tests/unittests/arnold/arnold_snmp_test.py
Labels: enhancement, snmpv3

#2746 Add link to our GitHub discussion forums
  doc/index.rst
Labels: documentation

#2750 Fix form validation with equal and in operator for adding expression with group to filter
  python/nav/web/alertprofiles/forms.py
  tests/integration/web/alertprofiles_test.py
Labels: bug

#2748 Make `navoidverify` and `naventity` commands SNMPv3 compatible
  bin/naventity
  bin/navoidverify
Labels: enhancement, snmpv3

#2743 Add initial SNMPv3 support to ipdevpoll
  python/nav/ipdevpoll/__init__.py
  python/nav/ipdevpoll/dataloader.py
  python/nav/ipdevpoll/jobs.py
  python/nav/ipdevpoll/plugins/snmpcheck.py
  python/nav/ipdevpoll/shadows/netbox.py
  python/nav/ipdevpoll/snmp/common.py
  python/nav/mibs/mibretriever.py
  python/nav/models/manage.py
  requirements/base.txt
  tests/unittests/ipdevpoll/snmp/__init__.py
  tests/unittests/ipdevpoll/snmp/common_test.py
Labels: enhancement, snmpv3, ipdevpoll

#2752 Add more expression operator tests for alert profiles and fix cleaning in ExpressionForm
  python/nav/web/alertprofiles/forms.py
  tests/integration/web/alertprofiles_test.py
Labels: bug

#2753 Remove unused function snmp_parameter_factory
  bin/naventity
  python/nav/ipdevpoll/snmp/common.py
Labels: snmpv3, cleanup

#2754 Remove deprecated Netbox SNMP properties
  python/nav/models/manage.py
  tests/integration/models/netbox_test.py
Labels: cleanup

#2751 Allow write-enabled SNMP profiles to be used for reading when no read-only profiles are available
  bin/naventity
  python/nav/arnold.py
  python/nav/ipdevpoll/snmp/common.py
  python/nav/models/manage.py
  python/nav/portadmin/snmp/base.py
  python/nav/web/portadmin/views.py
  tests/unittests/models/netbox_test.py
Labels: enhancement, snmpv3

#2756 Catch updating alert profile with non int id
  python/nav/web/alertprofiles/views.py
  tests/integration/web/alertprofiles_test.py
Labels: bug

#2761 Fix SeedDB edit netbox regression
  python/nav/web/seeddb/page/netbox/edit.py
  tests/integration/seeddb_test.py
Labels: bug

#2757 Add more validation for posting maintenance tasks
  python/nav/web/maintenance/forms.py
  python/nav/web/maintenance/utils.py
  python/nav/web/maintenance/views.py
  tests/integration/web/maintenance/views_test.py
Labels: bug

#2763 Fix SNMP v1/v2c regression in async libraries
  python/nav/ipdevpoll/snmp/common.py
Labels: bug, snmpv3

#2759 Frontend for configuring PoE in Portadmin
  python/nav/web/portadmin/utils.py
  python/nav/web/portadmin/views.py
  python/nav/web/static/js/src/portadmin.js
  python/nav/web/templates/portadmin/portlist.html
Labels: portadmin

#2764 Catch error when adding netbox with invalid ip
  python/nav/web/seeddb/page/netbox/edit.py
  python/nav/web/seeddb/page/netbox/forms.py
  tests/integration/seeddb_test.py
Labels: bug

#2765 Catch error when adding netbox with non existing profiles
  python/nav/web/seeddb/page/netbox/forms.py
  tests/integration/seeddb_test.py
Labels: bug

#2774 Do not make portadmin readonly if poe error
  python/nav/web/portadmin/views.py
Labels: bug, portadmin

#2776 Fix related names in PDU widget
  python/nav/web/navlets/forms.py
  tests/integration/widget_test.py
Labels: bug

#2777 Import sudo function from correct module
  python/nav/web/useradmin/views.py
  tests/integration/web/useradmin_test.py
Labels: bug
