Repository Uninett/nav, pull requests merged in 2024-10, with the labels that each got.

#3051 Remove adaptation for Django 1.8
  python/nav/models/fields.py
Labels: cleanup

#3058 Uncrispify AlertSubscriptionForm
  python/nav/web/alertprofiles/forms.py
  python/nav/web/templates/alertprofiles/subscription_form.html
Labels: refactor

#3064 Make it possible to use SubmitField for LabelSubmit
  python/nav/web/crispyforms.py
  python/nav/web/templates/custom_crispy_templates/submit_field.html
Labels: refactor

#3036 Uncrispify web info/search forms
  python/nav/web/crispyforms.py
  python/nav/web/info/forms.py
  python/nav/web/info/prefix/views.py
  python/nav/web/templates/custom_crispy_templates/flat_form.html
  python/nav/web/templates/info/base.html
  python/nav/web/templates/info/location/base.html
  python/nav/web/templates/info/netboxgroup/list_groups.html
  python/nav/web/templates/info/prefix/base.html
  python/nav/web/templates/info/room/base.html
  python/nav/web/templates/info/vlan/base.html
Labels: refactor

#3070 Uncrispify MatchFieldForm
  python/nav/web/alertprofiles/forms.py
  python/nav/web/templates/alertprofiles/base_detail.html
Labels: refactor

#3079 Fix branch specification for test workflow
  .github/workflows/build-and-test.yml
Labels: bug, github_actions

#3080 Uncrispify AlertAddressForm
  python/nav/web/alertprofiles/forms.py
Labels: refactor

#3088 Uncrispify LoginForm
  python/nav/web/templates/webfront/login.html
  python/nav/web/webfront/forms.py
Labels: refactor

#3086 Uncrispify FilterGroupForm
  python/nav/web/alertprofiles/forms.py
Labels: refactor

#3084 Uncrispify FilterForm
  python/nav/web/alertprofiles/forms.py
Labels: refactor

#3082 Uncrispify TimePeriodForm
  python/nav/web/alertprofiles/forms.py
  python/nav/web/templates/alertprofiles/timeperiod_edit.html
  python/nav/web/templates/alertprofiles/timeperiod_form.html
Labels: refactor

#3142 Fix PhantomJS test problems
  .github/workflows/build-and-test.yml
Labels: tests

#3139 Uncrispyfy NavbarlinkForm and NavbarLinkFormSet
  python/nav/web/sass/nav/my_account.scss
  python/nav/web/templates/webfront/_navbar_link_form.html
  python/nav/web/templates/webfront/preferences.html
  python/nav/web/webfront/forms.py
Labels: refactor

#3145 Use apt-get to install towncrier
  .github/workflows/towncrier.yml
Labels: bug

#3148 Use pipx to install towncrier
  .github/workflows/towncrier.yml
Labels: bug
