Repository Uninett/nav, pull requests merged in 2024-03, with the labels that each got.

#2831 Fix activeipcollector `get_timestamp` function implementation and its broken timezone-naive test
  python/nav/activeipcollector/manager.py
  tests/unittests/general/prefix_ip_collector_test.py
Labels: bug

#2853 Fix contrast in docs footer
  doc/_static/custom.css
Labels: documentation, frontend, uu

#2856 Remove warnings when building docs
  NOTES.rst
  doc/faq/faq.rst
  doc/hacking/adding-environment-probe-support.rst
  doc/reference/alerttypes.rst
  doc/reference/index.rst
  doc/reference/ipdevpoll.rst
  python/nav/mibs/mibretriever.py
  tox.ini
Labels: documentation, cleanup

#2827 Clean up overview/intro docs
  doc/intro/getting-organized.rst
  doc/intro/getting-started.rst
  doc/intro/install.rst
  doc/overview.rst
Labels: documentation

#2867 Remove nonsensical pydantic requirement
  pyproject.toml
Labels: cleanup

#2861 Preserve 500-error in test
  tests/integration/web/crawler_test.py
Labels: tests

#2868 Remove customization for definition lists
  doc/_static/custom.css
Labels: documentation, frontend

#2875 Fix broken `navclean` and `navsynctypes` scripts
  python/nav/bin/navclean.py
  python/nav/bin/navsynctypes.py
  tests/integration/bin_test.py
  tests/integration/conftest.py
  tests/requirements.txt
Labels: bug

#2878 Avoid running command line scripts twice on every invocation
  pyproject.toml
  python/nav/bin/navpgdump.py
  python/nav/bin/navsyncdb.py
  python/nav/bin/navtopology.py
Labels: bug
