Repository Uninett/nav, pull requests merged in 2024-09, with the labels that each got.

#2909 Remove Dict, List, Tuple and Type imports from Typing
  python/nav/Snmp/pynetsnmp.py
  python/nav/bin/navclean.py
  python/nav/eventengine/severity.py
  python/nav/ipdevpoll/plugins/modules.py
  python/nav/ipdevpoll/plugins/paloaltoarp.py
  python/nav/ipdevpoll/snmp/common.py
  python/nav/jwtconf.py
  python/nav/models/manage.py
  python/nav/napalm.py
  python/nav/portadmin/handlers.py
  python/nav/portadmin/napalm/juniper.py
  python/nav/portadmin/snmp/base.py
  python/nav/portadmin/snmp/cisco.py
  python/nav/web/alertprofiles/forms.py
  python/nav/web/portadmin/utils.py
  python/nav/web/utils.py
  tests/integration/conftest.py
Labels: cleanup

#2976 Replace session fakery by login simulation in Selenium functional tests
  python/nav/web/auth/utils.py
  tests/conftest.py
  tests/functional/conftest.py
  tests/integration/conftest.py
Labels: tests

#2978 Improve docs for developing with docker
  README.rst
  changelog.d/2978.changed.md
  doc/hacking/using-docker.rst
Labels: documentation

#2977 Restrict which branch pushes cause a full CI run
  .github/workflows/build-and-test.yml
Labels: tests

#2981 Uncrispyfy RoomFilterForm in seeddb
  python/nav/web/seeddb/forms/__init__.py
  python/nav/web/templates/seeddb/_filter_form.html
  python/nav/web/templates/seeddb/list.html
Labels: refactor

#2993 Remove crispy-forms from `VlanFilterForm`
  python/nav/web/seeddb/page/vlan.py
  python/nav/web/templates/seeddb/_filter_form_columns.html
  python/nav/web/templates/seeddb/list.html
Labels: refactor

#2987 Remove crispy-forms from `NetboxTypeFilterForm`
  python/nav/web/seeddb/forms/__init__.py
Labels: refactor

#2985 Remove unused `OrganizationFilterForm`
  python/nav/web/seeddb/forms/__init__.py
Labels: cleanup

#2969 Upgrade to newer Selenium for test suite
  tests/docker/Dockerfile
  tests/functional/geomap_test.py
  tests/functional/navbar_test.py
  tests/functional/room_test.py
  tests/functional/status_test.py
  tests/requirements.txt
Labels: tests

#2980 Fix RuntimeError when re-ordering filters within an Alert Profiles filter group
  changelog.d/2979.fixed.md
  python/nav/web/alertprofiles/views.py
  tests/integration/web/alertprofiles_test.py
Labels: bug, alertprofiles

#2966 "Un-parametrize" webcrawler tests
  changelog.d/2966.changed.md
  tests/integration/web/crawler_test.py
Labels: cleanup, tests

#3002 Change test suite web server (gunicorn) launch to a proper pytest fixture
  tests/conftest.py
  tests/functional/conftest.py
  tests/integration/conftest.py
  tests/integration/web/crawler_test.py
Labels: cleanup, tests, refactor

#3009 Use `isinstance` for instance checks instead of `type() ==`
  pyproject.toml
  tests/integration/snmptrapd_test.py
  tests/unittests/netmap/metadata_nx_test.py
Labels: cleanup

#3010 Replace ` == None` with `is None`
  pyproject.toml
  python/nav/bin/collect_active_ip.py
  python/nav/bin/emailreports.py
  python/nav/bin/navmain.py
  python/nav/bin/radiusparser.py
  python/nav/bin/servicemon.py
  python/nav/bin/start_arnold.py
  python/nav/ipdevpoll/plugins/juniperalarm.py
  python/nav/portadmin/snmp/cisco.py
  tests/integration/api_test.py
  tests/unittests/general/web_middleware_test.py
  tests/unittests/general/webfront_test.py
Labels: cleanup

#3011 Remove f-string without any placeholders
  pyproject.toml
  python/nav/web/sortedstats/config.py
  tests/unittests/portadmin/napalm/juniper_poe_test.py
Labels: cleanup

#3018 Remove unused imports in tests
  tests/integration/api_test.py
  tests/integration/bin_test.py
  tests/integration/models/alert_test.py
  tests/integration/models/fields_test.py
  tests/integration/models/netbox_test.py
  tests/integration/web/info_test.py
  tests/integration/web/templatesyntax_test.py
  tests/integration/widget_test.py
  tests/unittests/api/api_test.py
  tests/unittests/general/logengine_test.py
  tests/unittests/ipdevpoll/config_test.py
  tests/unittests/ipdevpoll/descrparsers_test.py
  tests/unittests/ipdevpoll/mibs_test.py
  tests/unittests/snmptrapd/weathergoose_test.py
  tests/unittests/statemon/icmp_test.py
  tests/unittests/watchdog/tests_test.py
  tests/unittests/web/sortedstats/sortedstatsconfig_test.py
  tests/unittests/web/webfront_test.py
Labels: cleanup

#3012 Switch from `not a in` to `a not in`
  pyproject.toml
  python/nav/bin/macwatch.py
  python/nav/ipdevpoll/plugins/sensors.py
  python/nav/web/geomap/graph.py
  python/nav/web/seeddb/utils/move.py
  tools/eventgenerators/moduleevent.py
  tools/eventgenerators/snmpevent.py
Labels: cleanup

#3021 Remove unused Django imports
  python/nav/bin/navdump.py
  python/nav/django/settings.py
  python/nav/models/fields.py
  python/nav/report/matrixIPv6.py
  python/nav/web/seeddb/page/prefix.py
  tools/eventgenerators/devicenotice.py
Labels: cleanup

#3024 Remove unused stdlib imports
  python/nav/arnold.py
  python/nav/bin/emailreports.py
  python/nav/bin/macwatch.py
  python/nav/bin/t1000.py
  python/nav/django/views.py
  python/nav/mibs/entity_mib.py
  python/nav/models/manage.py
  python/nav/statemon/checker/FtpChecker.py
  python/nav/util.py
  python/nav/web/auth/__init__.py
  python/nav/web/maintenance/views.py
Labels: cleanup

#3022 Simplify Xvfb bootstrap in test suite
  tests/requirements.txt
  tox.ini
Labels: cleanup, tests

#3015 Fix various test skip logic issues
  changelog.d/+skip-test-logic.fixed.md
  tests/integration/bin_test.py
  tests/integration/pping_test.py
  tests/integration/web/crawler_test.py
  tests/unittests/general/webfront_test.py
  tests/unittests/web/ldapauth_test.py
Labels: cleanup, tests

#3044 Use is instead of == to compare to True/False in tests
  tests/unittests/general/util_test.py
  tests/unittests/general/webfront_test.py
Labels: cleanup
