Repository Uninett/nav, pull requests merged in 2024-02, with the labels that each got.

#2799 Test pkg_resource usage
  python/nav/pgsync.py
  tests/unittests/buildconf_test.py
  tests/unittests/config_test.py
  tests/unittests/pgsync_test.py
Labels: upgrade, config, database, tests, refactor, dependencies

#2824 Upgrade sphinx to 5.3.0
  doc/conf.py
  requirements/base.txt
Labels: dependencies

#2823 Stop supporting Django's older than 3.2
  bin/smsd.py
  python/nav/auditlog/models.py
  python/nav/auditlog/utils.py
  python/nav/compatibility.py
  python/nav/django/legacy.py
  python/nav/django/settings.py
  python/nav/django/utils.py
  python/nav/ipdevpoll/storage.py
  python/nav/mibs/cisco_process_mib.py
  python/nav/mibs/itw_mib.py
  python/nav/models/fields.py
  python/nav/web/api/v1/alert_serializers.py
  python/nav/web/api/v1/views.py
  python/nav/web/auth/middleware.py
  python/nav/web/useradmin/forms.py
  requirements/django22.txt
  tests/integration/api_test.py
  tests/integration/models/model_test.py
  tests/integration/seeddb_test.py
  tests/integration/web/alertprofiles_test.py
  tests/integration/web/devicehistory_test.py
  tests/integration/web/ipdevinfo_test.py
  tests/integration/web/maintenance/views_test.py
  tests/integration/web/netboxtype_test.py
  tests/integration/web/prefixviewset_test.py
  tests/integration/web/webfront_test.py
Labels: dependencies

#2825 Use read the docs sphinx theme instead of bootstrap theme
  doc/_static/custom.css
  doc/conf.py
  doc/requirements.txt
Labels: documentation, discussion

#2830 Upgrade python-ldap from 3.4.0->3.4.4
  requirements/optional.txt
Labels: techdebt

#2832 Fix broken statemon tests
  tests/unittests/statemon/conftest.py
  tests/unittests/statemon/host_test.py
  tests/unittests/statemon/icmp_test.py
Labels: bug, tests

#2837 Show NAV logo on mobile in the docs
  doc/_static/custom.css
  doc/conf.py
  doc/templates/layout.html
  doc/templates/static/nav-logo.svg
Labels: documentation, frontend

#2840 Remove an adaptation to Pythons older than 3.7
  python/nav/web/auth/remote_user.py
Labels: upgrade

#2844 Remove deprecation warning for Django 4.0 in tests
  tests/integration/web/auth/conftest.py
  tests/integration/web/auth/middleware_test.py
  tests/integration/web/auth/sudo_test.py
Labels: tests, techdebt
