Repository Uninett/nav, pull requests merged in 2024-11, with the labels that each got.

#3110 Uncrispify MacWatchForm
  python/nav/web/crispyforms.py
  python/nav/web/macwatch/forms.py
  python/nav/web/templates/macwatch/addmacwatch.html
Labels: refactor

#3154 Uncrispify OrganizationAddForm in useradmin
  python/nav/web/templates/useradmin/account_detail.html
  python/nav/web/useradmin/forms.py
Labels: refactor

#3132 Uncrispify L2TraceForm
  python/nav/web/l2trace/forms.py
  python/nav/web/templates/l2trace/l2trace.html
Labels: refactor

#3161 Uncrispify TokenForm in user admin
  python/nav/web/templates/useradmin/token_edit.html
  python/nav/web/useradmin/forms.py
Labels: refactor

#3160 Uncrispify `GroupAddForm` in useradmin
  python/nav/web/templates/useradmin/account_detail.html
  python/nav/web/useradmin/forms.py
Labels: refactor

#3078 Uncrispify `ActivityIntervalForm` in ipdevinfo
  python/nav/web/ipdevinfo/forms.py
  python/nav/web/templates/ipdevinfo/modules.html
Labels: refactor

#3137 Uncrispify `StatusWidgetForm` in navlets
  python/nav/web/status2/forms.py
  python/nav/web/templates/navlets/status2_edit.html
Labels: refactor

#3129 Uncrispify ErrorLogSearchForm
  python/nav/web/radius/forms.py
  python/nav/web/templates/radius/error_log.html
Labels: refactor

#3130 Uncrispify AccountLogSearchForm
  python/nav/web/radius/forms.py
  python/nav/web/templates/radius/account_log.html
Labels: refactor

#3162 Uncrispify AccountChartsForm
  python/nav/web/radius/forms.py
  python/nav/web/templates/radius/account_charts.html
Labels: refactor

#3164 Uncrispify QuarantineVlanForm
  python/nav/web/arnold/forms.py
  python/nav/web/templates/arnold/quarantinevlans.html
Labels: refactor

#3173 Uncrispify Arnold SearchForm
  python/nav/web/arnold/forms.py
  python/nav/web/templates/arnold/search.html
Labels: refactor

#3188 Allow periods in room/location IDs in API
  changelog.d/3186.fixed.md
  python/nav/web/api/v1/views.py
  tests/integration/api_test.py
Labels: bug, api

#3128 Uncrispify all of seedDB
  python/nav/web/seeddb/forms/__init__.py
  python/nav/web/seeddb/page/service/edit.py
  python/nav/web/templates/seeddb/edit.html
  python/nav/web/templates/seeddb/edit_prefix.html
  python/nav/web/templates/seeddb/edit_vlan.html
  python/nav/web/templates/seeddb/list.html
  python/nav/web/templates/seeddb/service_netbox_form.html
  python/nav/web/templates/seeddb/service_property_form.html
Labels: refactor

#3106 Uncrispify LoggerGroupSearchForm
  python/nav/web/syslogger/forms.py
  python/nav/web/templates/syslogger/frag-search-form-fieldset.html
  python/nav/web/templates/syslogger/frag-search.html
Labels: refactor

#3183 Remove fallback form rendering from uncrispified forms
  python/nav/web/templates/alertprofiles/base_detail.html
  python/nav/web/templates/alertprofiles/subscription_form.html
  python/nav/web/templates/alertprofiles/timeperiod_edit.html
  python/nav/web/templates/alertprofiles/timeperiod_form.html
  python/nav/web/templates/arnold/justifications.html
  python/nav/web/templates/devicehistory/history_search.html
  python/nav/web/templates/devicehistory/history_view.html
  python/nav/web/templates/ipdevinfo/modules.html
  python/nav/web/templates/ipdevinfo/search.html
  python/nav/web/templates/ipdevinfo/sensor-details.html
  python/nav/web/templates/macwatch/addmacwatch.html
  python/nav/web/templates/maintenance/new_task.html
  python/nav/web/templates/messages/save.html
  python/nav/web/templates/navlets/alert_edit.html
  python/nav/web/templates/portadmin/base.html
  python/nav/web/templates/seeddb/netbox_wizard.html
  python/nav/web/templates/sortedstats/sortedstats.html
  python/nav/web/templates/status2/status.html
  python/nav/web/templates/threshold/set_threshold.html
  python/nav/web/templates/useradmin/group_detail.html
  python/nav/web/templates/webfront/login.html
  python/nav/web/templates/webfront/preferences.html
Labels: cleanup

#3187 Make `css_classes` argument optional for `FormRow`
  python/nav/web/crispyforms.py
  python/nav/web/templates/custom_crispy_templates/form_row.html
Labels: refactor

#3184 Remove unused imports from `crispy_forms_foundation`
  python/nav/web/useradmin/forms.py
Labels: cleanup

#3185 Remove unused loading of crispy_forms_tags in templates
  python/nav/web/templates/auditlog/base.html
  python/nav/web/templates/info/location/upload.html
  python/nav/web/templates/info/room/upload.html
  python/nav/web/templates/webfront/login.html
Labels: cleanup

#3181 Uncrispify `StyleFormTwo` in styleguide
  python/nav/web/styleguide.py
  python/nav/web/templates/styleguide.html
Labels: refactor

#3171 Uncrispify ManualDetentionForm
  python/nav/web/arnold/forms.py
  python/nav/web/templates/arnold/manualdetain-step2.html
Labels: refactor

#3197 Uncrispify portadmin navlet html template
  python/nav/web/templates/navlets/portadmin_view.html
Labels: refactor

#3195 Uncrispify graph edit navlet html template
  python/nav/web/templates/navlets/graph_edit.html
Labels: refactor

#3204 Remove now unused crispy `HelpField`
  python/nav/web/crispyforms.py
Labels: cleanup

#3203 Remove unused userinfo template
  python/nav/web/templates/useradmin/userinfo.html
Labels: cleanup

#3202 Uncrispify room map navlet html template
  python/nav/web/templates/navlets/room_map_view.html
Labels: refactor

#3196 Uncrispify DetentionProfileForm
  python/nav/web/arnold/forms.py
  python/nav/web/templates/arnold/edit_detention_profile.html
Labels: refactor

#3198 Uncrispify room/location status navlet html template
  python/nav/web/templates/navlets/room_location_status_edit.html
Labels: refactor

#3210 Rename `FormCheckBox` to `CheckBox`
  python/nav/web/arnold/forms.py
  python/nav/web/crispyforms.py
Labels: cleanup

#3209 Remove unused crispy `CheckBox`
  python/nav/web/arnold/forms.py
  python/nav/web/crispyforms.py
Labels: cleanup

#3208 Remove unused css classes `checkboxinput`/`input-align`
  python/nav/web/sass/nav/custom.scss
Labels: cleanup

#3212 Fix typo in arnold justifications
  python/nav/web/arnold/forms.py
  python/nav/web/arnold/urls.py
  python/nav/web/arnold/views.py
  python/nav/web/templates/arnold/justifications.html
  python/nav/web/templates/arnold/tabs.html
Labels: cleanup

#3176 Remove `setup.py` once and for all
  changelog.d/3176.changed.md
  doc/howto/generic-install-from-source.rst
  doc/howto/manual-install-on-debian.rst
  setup.py
  tools/docker/build.sh
Labels: cleanup

#3028 Remove unused error variables
  python/nav/bin/macwatch.py
  python/nav/bin/radiusparser.py
  python/nav/bin/snmptrapd.py
  python/nav/eventengine/severity.py
  python/nav/eventengine/topology.py
  python/nav/portadmin/snmp/base.py
  python/nav/portadmin/snmp/cisco.py
  python/nav/smsd/gammudispatcher.py
  python/nav/statemon/checker/MysqlChecker.py
  python/nav/statemon/db.py
Labels: cleanup

#3219 Update ruff in pre-commit to newest version
  .pre-commit-config.yaml
Labels: dependencies

#3211 Remove `crispy-forms-foundation` and `django-crispy-forms` from requirements
  NOTES.rst
  changelog.d/2794.removed.md
  python/nav/django/settings.py
  python/nav/web/crispyforms.py
  requirements/base.txt
Labels: cleanup, dependencies

#3227 Fix obsolete crispy-forms references in UI styleguide
  python/nav/web/templates/styleguide.html
Labels: cleanup

#3224 Upgrade chrome-driver version in docker image to 131.0.6778.69
  tests/docker/Dockerfile
Labels: docker, tests, dependencies

#3226 Fix broken `__eq__` implementation of Netbox stub class
  changelog.d/3225.fixed.md
  python/nav/netmap/stubs/__init__.py
  tests/unittests/netmap/stubs_test.py
Labels: bug, netmap

#3223 Use tox 4 to run test suite
  .github/workflows/build-and-test.yml
  changelog.d/2973.changed.md
  doc/hacking/hacking.rst
  tests/docker/Dockerfile
  tests/docker/test.sh
  tox.ini
Labels: tests, dependencies

#3232 Show error message on trying to delete last dashboard
  python/nav/web/static/js/src/webfront.js
  python/nav/web/webfront/views.py
  tests/integration/web/webfront_test.py
Labels: bug

#3233 Disable deleting of default dashboard
  changelog.d/3150.fixed.md
  python/nav/web/webfront/views.py
  tests/integration/web/webfront_test.py
Labels: bug

#3033 Remove unused test variables
  tests/unittests/django/templatetags/info_test.py
  tests/unittests/general/bulkparse_test.py
  tests/unittests/ipdevpoll/prefix_test.py
  tests/unittests/models/fields_test.py
  tests/unittests/netmap/metadata_nx_test.py
  tests/unittests/netmap/topology_layer2_testcase.py
  tests/unittests/netmap/topology_layer3_testcase.py
  tests/unittests/web/ldapauth_test.py
Labels: cleanup

#3026 Add `F401` (unused imports) rule to ruff config
  pyproject.toml
Labels: discussion

#3237 Update pytest and plugin versions
  tests/requirements.txt
Labels: cleanup, tests, dependencies

#3236 Ensure every account has exactly one default dashboard
  changelog.d/+migration-one-default-dashboard.fixed.md
  python/nav/models/sql/changes/sc.05.12.0001.sql
  python/nav/models/sql/changes/sc.05.12.0002.sql
Labels: bug, sql, database

#3234 Hide "Delete dashboard" button for default dashboard
  python/nav/web/static/js/src/webfront.js
  python/nav/web/templates/webfront/index.html
Labels: bug, discussion

#3239 Update list limits for alert profiles dropdowns
  changelog.d/2908.fixed.md
  python/nav/models/sql/changes/sc.05.12.0100.sql
Labels: bug

#3235 Cancel scheduled maintenance tasks when all their components are missing
  changelog.d/3229.added.md
  python/nav/maintengine.py
  tests/integration/maintengine_test.py
Labels: enhancement, maintengine

#3240 Make alert profiles match value dropdown lists searchable using `select2`
  changelog.d/3238.added.md
  python/nav/web/alertprofiles/forms.py
Labels: enhancement

#3231 Refactor maintenance task views to improve display of deleted components #3230
  changelog.d/3228.fixed.md
  python/nav/django/templatetags/maintenance.py
  python/nav/models/fields.py
  python/nav/models/manage.py
  python/nav/models/msgmaint.py
  python/nav/models/sql/changes/sc.05.12.0010.sql
  python/nav/web/maintenance/utils.py
  python/nav/web/maintenance/views.py
  python/nav/web/templates/maintenance/details.html
  python/nav/web/templates/maintenance/frag-component-trail.html
  python/nav/web/templates/maintenance/new_task.html
Labels: maintenance, cleanup

#3035 Adds unused variable rule (`F841`) to ruff
  pyproject.toml
Labels: discussion

#3045 Use default rules for ruff
  pyproject.toml
Labels: cleanup, discussion
