Repository Uninett/nav, pull requests merged in 2024-05, with the labels that each got.

#2889 Update PostgreSQL requirement to version 11
  .github/workflows/build-and-test.yml
  NOTES.rst
  changelog.d/+pg11.changed
  doc/howto/generic-install-from-source.rst
  docker-compose.yml
Labels: dependencies

#2893 Add deprecation warnings for Python 3.7 in upcoming feature releases
  NOTES.rst
  changelog.d/+py37-deprecation.deprecated.md
Labels: deprecation

#2898 Add back missing delete icon for form selectors
  changelog.d/2898.fixed.md
  python/nav/web/sass/nav/_select2.scss
Labels: bug

#2907 Remove all IRC channel references from documentation
  README.rst
  changelog.d/2907.removed.md
  doc/hacking/hacking.rst
  doc/hacking/release-procedure.rst
  doc/index.rst
Labels: documentation

#2613 Palo Alto ARP table plugin
  NOTES.rst
  changelog.d/2613.added.md
  doc/reference/ipdevpoll.rst
  python/nav/etc/ipdevpoll.conf
  python/nav/ipdevpoll/plugins/paloaltoarp.py
  requirements/base.txt
  tests/unittests/ipdevpoll/plugins_paloaltoarp_test.py
Labels: arp, PaloAlto

#2919 Also deprecate Python 3.8
  NOTES.rst
  changelog.d/+py37-deprecation.deprecated.md
Labels: documentation, deprecation

#2913 Delay ARP record closures for devices that have been down for a while
  changelog.d/2913.fixed.md
  doc/reference/backend-processes.rst
  python/nav/bin/navclean.py
  python/nav/etc/cron.d/dbclean
  python/nav/models/sql/changes/sc.05.10.0001.sql
Labels: bug

#2928 Reinstate database rule `netbox_close_arp` and delete `netbox_status_close_arp` instead
  changelog.d/2910.fixed.md
  python/nav/models/sql/changes/sc.05.10.0002.sql
Labels: bug
