Repository Uninett/nav, pull requests merged in 2025-08, with the labels that each got.

#3421 Rename codecov config file
  codecov.yml
Labels: nonews

#2897 Add QR Code link to 'My Stuff'
  changelog.d/2897.added.md
  python/nav/web/sass/nav.scss
  python/nav/web/sass/nav/_qr_code.scss
  python/nav/web/templates/base.html
  python/nav/web/templates/webfront/_qr_code.html
  python/nav/web/utils.py
  python/nav/web/webfront/urls.py
  python/nav/web/webfront/views.py
  tests/integration/web/webfront_test.py
  tests/unittests/web/qrcode_test.py
Labels: frontend

#2899 Make it possible to download a ZIP file containing QR codes of bulk selected netboxes/rooms
  changelog.d/+qr-code-bulk.added.md
  python/nav/web/seeddb/__init__.py
  python/nav/web/seeddb/page/__init__.py
  python/nav/web/seeddb/page/netbox/__init__.py
  python/nav/web/seeddb/page/room.py
  python/nav/web/templates/seeddb/list.html
  python/nav/web/utils.py
  tests/integration/seeddb_test.py
  tests/unittests/web/qrcode_test.py
Labels: blocked, frontend

#3417 Slightly update information about test suites
  doc/hacking/hacking.rst
Labels: documentation, nonews

#3420 Document practical usage of devcontainer
  Makefile
  changelog.d/3398.added.md
  doc/hacking/hacking.rst
  doc/hacking/index.rst
  doc/hacking/using-devcontainers.rst
  doc/howto/commandline-utilities.rst
Labels: documentation

#3385 Implement ipdevinfo UI for ipdevpoll job refreshing
  changelog.d/3350.added.md
  python/nav/web/ipdevinfo/urls.py
  python/nav/web/ipdevinfo/views.py
  python/nav/web/sass/nav/ipdevinfo.scss
  python/nav/web/static/js/src/ipdevinfo.js
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo-alert-box.html
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo-refresh-button.html
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo-refresh-ongoing-button.html
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
Labels: htmx

#3453 Add Simen Abelsen to contributor lists
  AUTHORS.rst
  python/nav/web/templates/webfront/about.html
Labels: documentation, nonews

#3456 Add developer script to re-generate JWT signing keys
  doc/hacking/using-devcontainers.rst
  tools/reset-jwt-keys.sh
Labels: nonews

#3469 Fix Python 3.12 SyntaxWarnings
  python/nav/bin/radiusparser.py
  python/nav/smidumps/DNOS-SWITCHING-MIB.py
Labels: cleanup, nonews

#3470 Mark TestData namedtuple as *not a test case*
  tests/unittests/dhcpstats/kea_dhcp_test.py
Labels: cleanup, nonews

#3460 Replace foundation equalizer with jquery
  changelog.d/3477.changed.md
  python/nav/web/static/js/src/netmap/control_view.js
Labels: cleanup, javascript

#3483 Clean up devcontainer dumpster fire
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
Labels: docker, nonews
