Repository Uninett/nav, pull requests merged in 2025-03, with the labels that each got.

#3296 Add dot-files that git must keep to .gitignore
  .gitignore
Labels: nonews

#3261 Add tests for device history search
  changelog.d/3261.added.md
  tests/integration/web/devicehistory_test.py
Labels: tests

#3289 Validate number of days in account log search form
  changelog.d/3247.fixed.md
  python/nav/web/radius/forms.py
  tests/integration/web/radius_test.py
Labels: bug

#3323 Credit Jørund as a contributor
  AUTHORS.rst
  python/nav/web/templates/webfront/about.html
Labels: documentation, nonews

#3333 Fix broken functional tests on GitHub actions
  tests/functional/conftest.py
Labels: nonews

#3334 Stop installing Chrome and chromedriver explicitly into github workflows
  .github/workflows/build-and-test.yml
  tox.ini
Labels: nonews
