Repository Uninett/nav, pull requests merged in 2025-05, with the labels that each got.

#3327 Fix documentation page sidebar bug
  doc/howto/mod_auth_mellon_feide.rst
  doc/howto/mod_auth_openidc_feide.rst
  doc/reference/web_authentication.rst
Labels: nonews

#3268 Add model for JWT refresh token
  changelog.d/3268.added.md
  python/nav/models/api.py
  python/nav/models/sql/changes/sc.05.14.0001.sql
  python/nav/web/jwtgen.py
  tests/unittests/models/jwtrefreshtoken_test.py
  tests/unittests/web/jwtgen_test.py
Labels: JWT

#3299 Stop using pylint
  doc/hacking/hacking.rst
  python/pylint.rc
  tests/docker/Makefile
  tests/docker/run.sh
  tests/docker/scripts/pylint.sh
  tests/docker/test.sh
  tests/requirements.txt
  tox.ini
Labels: tests, nonews

#3280 Remove unused `ColumnsForm`
  changelog.d/3243.removed.1.md
  python/nav/models/profiles.py
  python/nav/models/sql/changes/sc.05.14.0002.sql
  python/nav/web/templates/webfront/preferences.html
  python/nav/web/webfront/__init__.py
  python/nav/web/webfront/forms.py
  python/nav/web/webfront/urls.py
  python/nav/web/webfront/views.py
Labels: cleanup

#3341 Comply with PEP 639 license spec
  pyproject.toml
Labels: nonews

#3342 Set default Django version for testing
  tox.ini
Labels: nonews

#3364 Lock MegaLinter to v8.6.0
  .github/workflows/linter.yml
Labels: github_actions

#3365 Fix ReadTheDocs builds
  .readthedocs.yaml
  constraints.txt
  pyproject.toml
Labels: documentation, nonews

#3363 Upgrade NAPALM to 5.0
  NOTES.rst
  changelog.d/2358.changed.md
  pyproject.toml
  requirements/base.txt
Labels: dependencies

#3376 Add read-only for non-admin and read-write for admin permission class
  python/nav/web/api/v1/auth.py
  python/nav/web/api/v1/views.py
Labels: nonews

#3379 Remove full path names from command examples
  doc/howto/migrate-data.rst
Labels: documentation, nonews
