Repository Uninett/nav, pull requests merged in 2025-02, with the labels that each got.

#3278 Skip towncrier check on `github_action` label
  .github/workflows/towncrier.yml
Labels: github_actions

#3279 Limit interval in switch port activity to 10000
  changelog.d/3242.fixed.md
  python/nav/web/ipdevinfo/forms.py
Labels: bug

#3282 Clean/check number of days in activity interval form
  changelog.d/3242.fixed.md
  python/nav/web/ipdevinfo/forms.py
  tests/integration/web/ipdevinfo_test.py
Labels: bug

#3286 Upgrade development Docker environment to Debian Bookworm / Python 3.11
  Dockerfile
  changelog.d/3284.changed.md
  docker-compose.snmp.yml
  docker-compose.yml
  tools/docker/build.sh
  tools/docker/doc-watch.sh
Labels: docker

#3288 Upgrade auxiliary Docker images to Debian Bookworm
  changelog.d/+auxiliary-docker-bookworm.changed.md
  tools/docker/graphite/Dockerfile
  tools/forward/Dockerfile
Labels: docker

#3272 Fix room map widget search not doing anything
  changelog.d/3207.fixed.md
  python/nav/web/navlets/room_map.py
Labels: bug

#3255 Upgrade test container image to Ubuntu 24.04
  tests/docker/Dockerfile
  tests/docker/Makefile
  tests/docker/scripts/entrypoint.sh
Labels: nonews

#3281 Check that vlan is not already quarantined in Arnold
  changelog.d/3244.fixed.md
  python/nav/web/arnold/forms.py
  tests/integration/web/arnold_test.py
Labels: bug

#3277 Ignore case of sysname in IP device info
  changelog.d/3262.fixed.md
  python/nav/web/ipdevinfo/views.py
  tests/integration/web/ipdevinfo_test.py
Labels: bug

#3291 Add user-agent header when downloading OUI textfile
  changelog.d/3291.fixed.md
  python/nav/bin/update_ouis.py
Labels: bug

#3294 Stop wiping apt cache after every apt command in development Docker image
  Dockerfile
Labels: nonews

#3285 Clean number of days in account charts form
  changelog.d/3245.fixed.md
  python/nav/web/radius/forms.py
  tests/integration/web/radius_test.py
Labels: bug
