Repository Uninett/nav, pull requests merged in 2025-09, with the labels that each got.

#3462 Replace foundation tooltips with custom implementation
  changelog.d/3449.added.md
  python/nav/web/sass/nav.scss
  python/nav/web/sass/nav/_tooltip.scss
  python/nav/web/static/js/src/info_room.js
  python/nav/web/static/js/src/main.js
  python/nav/web/static/js/src/plugins/tooltip.js
  python/nav/web/static/js/src/portadmin.js
  python/nav/web/templates/alertprofiles/filter_form.html
  python/nav/web/templates/alertprofiles/matchfield_form.html
  python/nav/web/templates/alertprofiles/timeperiods.html
  python/nav/web/templates/custom_crispy_templates/field_helptext_as_icon.html
  python/nav/web/templates/foundation-5/field.html
  python/nav/web/templates/info/room/netboxview.html
  python/nav/web/templates/ipdevinfo/frag-disclaimer.html
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
  python/nav/web/templates/l2trace/l2trace.html
  python/nav/web/templates/machinetracker/mac_tracker.html
  python/nav/web/templates/webfront/index.html
Labels: cleanup, javascript, discussion

#3490 Add type annotations to authentication system
  python/nav/web/auth/__init__.py
  python/nav/web/auth/ldap.py
  python/nav/web/auth/middleware.py
  python/nav/web/auth/sudo.py
  python/nav/web/webfront/views.py
Labels: cleanup, nonews

#3494 Replace search hint modals in Radius tool
  changelog.d/3494.changed.md
  python/nav/web/radius/urls.py
  python/nav/web/radius/views.py
  python/nav/web/templates/radius/_account_chart_hints_modal.html
  python/nav/web/templates/radius/_account_log_hints_modal.html
  python/nav/web/templates/radius/_error_log_hints_modal.html
  python/nav/web/templates/radius/account_charts.html
  python/nav/web/templates/radius/account_log.html
  python/nav/web/templates/radius/error_log.html
  tests/integration/web/radius_test.py
Labels: refactor, modernisation, htmx

#3512 Adjust close modal icon to avoid text overlap
  changelog.d/+42a720f9.fixed.md
  python/nav/web/sass/nav/_modal.scss
Labels: cleanup

#3505 Replace ipdevinfo modals
  changelog.d/+da97b5a4.changed.md
  python/nav/web/ipdevinfo/urls.py
  python/nav/web/ipdevinfo/views.py
  python/nav/web/templates/ipdevinfo/_poe_classification_hint_modal.html
  python/nav/web/templates/ipdevinfo/_poe_status_hint_modal.html
  python/nav/web/templates/ipdevinfo/frag-hostinfo.html
  python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
  python/nav/web/templates/ipdevinfo/poegroup-details.html
  tests/integration/web/ipdevinfo_test.py
Labels: cleanup, modernisation, htmx

#3521 Replace threshold help modal with htmx
  changelog.d/+9652911e.changed.md
  python/nav/web/templates/threshold/_threshold_help_modal.html
  python/nav/web/templates/threshold/set_threshold.html
  python/nav/web/threshold/urls.py
  python/nav/web/threshold/views.py
  tests/integration/web/threshold_test.py
Labels: cleanup, javascript, htmx

#3525 Show distinct filter groups in "Groups and Permissions" modal in alert profiles
  changelog.d/3523.fixed.md
  python/nav/web/alertprofiles/views.py
Labels: cleanup

#3526 Fix bug where QR Code button is not clickable
  changelog.d/+cc270e47.fixed.md
  python/nav/web/static/js/src/main.js
Labels: javascript

#3511 Replace import dashboard modal
  changelog.d/+b607de92.changed.md
  python/nav/web/static/js/src/webfront.js
  python/nav/web/templates/webfront/_import_dashboard_form_modal.html
  python/nav/web/templates/webfront/index.html
  python/nav/web/webfront/urls.py
  python/nav/web/webfront/views.py
  tests/integration/web/webfront_test.py
Labels: cleanup, javascript, htmx

#3528 Add new components to styleguide
  python/nav/web/templates/styleguide.html
Labels: documentation, cleanup, nonews

#3514 Replace radius detail modals with htmx
  changelog.d/3514.changed.md
  python/nav/web/radius/views.py
  python/nav/web/static/js/src/radius.js
  python/nav/web/templates/radius/account_log.html
  python/nav/web/templates/radius/detail_modal.html
  python/nav/web/templates/radius/details_table.html
  python/nav/web/templates/radius/error_log.html
  tests/integration/web/radius_test.py
Labels: cleanup, javascript, htmx

#3467 Test on Django 5.2, Python 3.13
  .github/workflows/build-and-test.yml
  .sonarcloud.properties
  changelog.d/3467.added.md
  pyproject.toml
  requirements/base.txt
  requirements/django50.txt
  requirements/django51.txt
  requirements/django52.txt
  tests/docker/Dockerfile
  tox.ini
Labels: upgrade, django, psycopg, dependencies

#3546 Add ruff extention to vscode part in devcontainer
  .devcontainer/devcontainer.json
Labels: nonews

#3549 Show error messages from backend in network explorer
  python/nav/web/static/js/src/networkexplorer.js
Labels: javascript, nonews

#3550 Add support for positioning popover on multiple sides
  changelog.d/3550.added.md
  python/nav/web/sass/nav/_popover.scss
  python/nav/web/templates/styleguide.html
Labels: cleanup, modernisation

#3543 Remove foundation vendor js
  changelog.d/3542.removed.md
  python/nav/web/static/js/libs/fastclick.js
  python/nav/web/static/js/libs/foundation.min.js
  python/nav/web/static/js/libs/modernizr.js
  python/nav/web/static/js/require_config.js
  python/nav/web/static/js/src/ipam/app.js
  python/nav/web/static/js/src/ipam/views/subnetallocator.js
  python/nav/web/static/js/src/machinetracker.js
  python/nav/web/static/js/src/main.js
  python/nav/web/static/js/src/plugins/seeddb_datatables.js
  python/nav/web/static/js/src/plugins/seeddb_map.js
  python/nav/web/static/js/src/seeddb.js
Labels: cleanup, javascript

#3552 Strip null-bytes from bytestrings being made safe for PostgreSQL
  changelog.d/2479.added.md
  python/nav/Snmp/__init__.py
Labels: snmp
