Repository Uninett/nav, pull requests merged in 2025-07, with the labels that each got.

#3308 Add a pull request template
  .github/pull_request_template.md
Labels: discussion, github_actions

#3343 Add a devcontainer definition
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/scripts/init-nav-config.sh
  .gitignore
Labels: nonews

#3386 Add HTMX 2.0.4 and Django-HTMX to NAV
  changelog.d/386.added.md
  pyproject.toml
  python/nav/django/settings.py
  python/nav/web/static/js/libs/htmx-2.0.4.min.js
  python/nav/web/templates/base.html
  requirements/base.txt
Labels: htmx

#3366 Remove unused template
  python/nav/web/templates/ipam/includes/find_subnet.html
Labels: cleanup, nonews

#3411 Add rule "line-too-long" to ruff
  .pre-commit-config.yaml
  pyproject.toml
  python/nav/Snmp/profile.py
  python/nav/bin/radiusparser.py
  python/nav/django/templatetags/info.py
  python/nav/eventengine/severity.py
  python/nav/ipdevpoll/plugins/psu.py
  python/nav/models/api.py
  python/nav/models/profiles.py
  python/nav/report/generator.py
  python/nav/web/crispyforms.py
  python/nav/web/geomap/db.py
  python/nav/web/info/searchproviders.py
  python/nav/web/jwtgen.py
  python/nav/web/portadmin/views.py
  tests/integration/eventengine/juniper_alert_count_test.py
  tests/integration/ipdevpoll/plugins/paloaltoarp_test.py
  tests/integration/mibs/juniper_alarm_mib_test.py
  tests/integration/seeddb_test.py
  tests/integration/update_ouis_test.py
  tests/integration/web/alertprofiles_test.py
  tests/integration/web/devicehistory_test.py
  tests/integration/web/geomap_test.py
  tests/integration/web/graphite_test.py
  tests/integration/web/radius_test.py
  tests/unittests/Snmp/Snmp_test.py
  tests/unittests/config_test.py
  tests/unittests/general/logengine_test.py
  tests/unittests/ipdevpoll/system_test.py
  tests/unittests/jwtconf_test.py
  tests/unittests/models/jwtrefreshtoken_test.py
  tests/unittests/models/netbox_test.py
  tests/unittests/netmap/multidigraph_to_undirect_test.py
  tests/unittests/pgsync_test.py
  tests/unittests/portadmin/napalm/juniper_poe_test.py
  tests/unittests/statemon/db_test.py
  tests/unittests/statemon/icmp_test.py
  tests/unittests/web/jwtgen_test.py
  tools/eventgenerators/snmpevent.py
Labels: nonews

#3367 Add csrf token to forms in alert profiles
  python/nav/web/templates/alertprofiles/account_detail.html
  python/nav/web/templates/alertprofiles/base_detail.html
  python/nav/web/templates/alertprofiles/base_list.html
  python/nav/web/templates/alertprofiles/expression_form.html
  python/nav/web/templates/alertprofiles/permissions.html
  python/nav/web/templates/alertprofiles/profile.html
  python/nav/web/templates/alertprofiles/profile_detail.html
  python/nav/web/templates/alertprofiles/subscription_form.html
Labels: nonews

#3388 Add csrf token to forms in useradmin
  python/nav/web/templates/base.html
  python/nav/web/templates/useradmin/account_detail.html
  python/nav/web/templates/useradmin/delete.html
  python/nav/web/templates/useradmin/token_edit.html
Labels: refactor, nonews

#3389 Add csrf token to forms in SeedDB
  python/nav/web/templates/seeddb/bulk_import.html
  python/nav/web/templates/seeddb/delete.html
  python/nav/web/templates/seeddb/edit_patch.html
  python/nav/web/templates/seeddb/list.html
  python/nav/web/templates/seeddb/move.html
Labels: refactor, nonews

#3390 Add csrf token to forms in search
  python/nav/web/templates/info/event/details.html
  python/nav/web/templates/info/images/upload.html
  python/nav/web/templates/info/netboxgroup/group_edit.html
  python/nav/web/templates/info/prefix/details.html
  python/nav/web/templates/info/room/fragment_add_sensor.html
  python/nav/web/templates/info/room/fragment_add_sensors_sum.html
  python/nav/web/templates/info/room/fragment_add_sensorsdiff.html
  python/nav/web/templates/info/room/fragment_rack.html
  python/nav/web/templates/info/room/netboxview.html
  python/nav/web/templates/info/room/roominfo_racks.html
Labels: refactor, nonews
